// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0kihxF68F36PtvaQhs8haqsbjGH8QCZw',
    appId: '1:260148323296:web:9d53e17201fb49af990185',
    messagingSenderId: '260148323296',
    projectId: 'chatgpt-819fd',
    authDomain: 'chatgpt-819fd.firebaseapp.com',
    storageBucket: 'chatgpt-819fd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDklySk0dvuJzo7TcYenfcfG7SSVNx6-DY',
    appId: '1:260148323296:android:752bfec353bf6b64990185',
    messagingSenderId: '260148323296',
    projectId: 'chatgpt-819fd',
    storageBucket: 'chatgpt-819fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg19ef7nYIK3Fs-a5NZybWbMhu4P_gCzo',
    appId: '1:260148323296:ios:bb5042e571c62ad1990185',
    messagingSenderId: '260148323296',
    projectId: 'chatgpt-819fd',
    storageBucket: 'chatgpt-819fd.appspot.com',
    iosClientId: '260148323296-a3f4asmhs49q3fpp7qv1t2061ooe76sq.apps.googleusercontent.com',
    iosBundleId: 'com.example.gptApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg19ef7nYIK3Fs-a5NZybWbMhu4P_gCzo',
    appId: '1:260148323296:ios:bb5042e571c62ad1990185',
    messagingSenderId: '260148323296',
    projectId: 'chatgpt-819fd',
    storageBucket: 'chatgpt-819fd.appspot.com',
    iosClientId: '260148323296-a3f4asmhs49q3fpp7qv1t2061ooe76sq.apps.googleusercontent.com',
    iosBundleId: 'com.example.gptApp',
  );
}
